// This file is generated by npm run gen:icons

export type IconName =
	| "add_notes-fill"
	| "add_notes"
	| "arrow_left"
	| "category-fill"
	| "category"
	| "edit"
	| "home-fill"
	| "home"
	| "login-logo"
	| "person-fill"
	| "person"
	| "Search"
	| "widgets"